ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS current_status TEXT NOT NULL DEFAULT 'offline';
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_tag INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS spycat_karma INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS color_accent TEXT NOT NULL DEFAULT '#f3a51a';
ALTER TABLE users ADD COLUMN IF NOT EXISTS compact_grid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS spike_sound BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE products ADD COLUMN IF NOT EXISTS old_price NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS review_score_desc TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS positive_percent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS genres TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS gameplay_hours INTEGER NOT NULL DEFAULT 15;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_coop BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE direct_chats ADD COLUMN IF NOT EXISTS pinned_message_id INTEGER;
ALTER TABLE direct_messages ADD COLUMN IF NOT EXISTS reactions JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE room_members ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'member';
ALTER TABLE room_members ADD COLUMN IF NOT EXISTS joined_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE messages ADD COLUMN IF NOT EXISTS reply_author TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS reply_content TEXT;

ALTER TABLE market_listings ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '';
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP;
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP;
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS seller_risk_score_snapshot INTEGER NOT NULL DEFAULT 0;
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS seller_flag_snapshot TEXT NOT NULL DEFAULT 'none';
ALTER TABLE market_trades ADD COLUMN IF NOT EXISTS seller_flag_note_snapshot TEXT NOT NULL DEFAULT '';

ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS resolved_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS resolution TEXT;
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS moderator_note TEXT NOT NULL DEFAULT '';
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS payout_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS payout_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS payout_note TEXT NOT NULL DEFAULT '';
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS risk_score_snapshot INTEGER NOT NULL DEFAULT 0;
ALTER TABLE market_disputes ADD COLUMN IF NOT EXISTS risk_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'direct_chats_pinned_message_fk'
  ) THEN
    ALTER TABLE direct_chats
      ADD CONSTRAINT direct_chats_pinned_message_fk
      FOREIGN KEY (pinned_message_id) REFERENCES direct_messages(id) ON DELETE SET NULL;
  END IF;
END $$;
